import type { NextPage } from "next";
import Head from "next/head";

import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data } = useSession();
  return (
    <div>
      <Head>
        <title>Creative Nepal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data?.user ? (
        <>
          <h1>Hello {data?.user?.name}</h1>
          <button onClick={() => signOut()}>Sign out</button>
        </>
      ) : (
        <button onClick={() => signIn("google")}>Signin</button>
      )}
    </div>
  );
};

export default Home;
